name: 'Generate SBOM for All Repos in Org'
description: 'Generate an SBOM via the REST API for all repos in an org'
author: 'Josh Johanning'
branding:
  color: green
  icon: shield
inputs:
  token:
    required: true
    description: 'GitHub token with permissions to read SBOMs from repos in the org - github.token will only bring in public repos SBOMs'
runs:
  using: 'node16'
  main: 'dist/index.js'
